services:
  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always
